### ISSUE TITLE
404 in readme

### ISSUE THREAD

**Issue by paulirish** [auchenberg/chrome-devtools-app#43]
https://github.com/auchenberg/chrome-devtools-app/raw/master/build/Chrome%20DevTools/osx/Chrome-DevTools.app.zip is in the readme and it 404s

**Comment by paulirish** [comment]
also `bower install` is required (now)

**Comment by auchenberg** [comment]
Aha. Needs a refresh after I merged the migration to electron in. Coming up.

**Comment by auchenberg** [comment]
Fixed in https://github.com/auchenberg/chrome-devtools-app/commit/4ad8e242fbead21aa42f2e67f05c831c07d7d1e6, https://github.com/auchenberg/chrome-devtools-app/commit/4ad8e242fbead21aa42f2e67f05c831c07d7d1e6, https://github.com/auchenberg/chrome-devtools-app/commit/793500c01f8bb29015a736c79cc8d3e4322558bd, https://github.com/auchenberg/chrome-devtools-app/commit/e0f596b8bad980a3c8c4cc5ef6973ab564529ec6, https://github.com/auchenberg/chrome-devtools-app/commit/2fa6e5d6a9c171781c72ff5459dc2b21b411766d
